### ISSUE TITLE
Improve pins

### ISSUE THREAD

**Issue by saraedum** [conda-forge/cppyy-feedstock#6]
The latest cppyy package does not work with the first cppy-cling packaged here. I have not checked where the problem is exactly but we should improve the pins.

**Comment by wlav** [comment]
In the setup.py files, I typically leave a 'large than' selection for the dependencies. This was okay in the past, but upstream has finally started to take up several patches I provided, but not always exactly the same.

Would it help if I moved the version selection in the setup.py files to 'equal's? I.e. pick one and only one version? (The only way that could clash, is when mixing python and pypy in the same environment, as pypy support is behind, so needs older versions of the backend.)

**Comment by saraedum** [comment]
I now set the pins to the values that the setup.py specifies i.e. exact pins.
